# Generated by Django 3.0.5 on 2020-05-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
