# Generated by Django 3.0.5 on 2020-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='transition',
            name='checklist',
            field=models.ManyToManyField(to='project_management_portal.Checklist'),
        ),
    ]
