# Generated by Django 3.0.5 on 2020-06-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0004_auto_20200602_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='workflow_type',
            new_name='workflow',
        ),
    ]
