# Generated by Django 3.0.5 on 2020-06-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0005_auto_20200602_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='conditons_satisfied',
            field=models.ManyToManyField(to='project_management_portal.Checklist'),
        ),
    ]
