# Generated by Django 3.0.5 on 2020-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0006_task_conditons_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Developer Story', 'Developer Story'), ('User Story', 'User Story'), ('Enhancement', 'Enhancement')], max_length=100),
        ),
    ]
