# Generated by Django 3.0.5 on 2020-06-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0007_auto_20200604_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='conditons_satisfied',
            new_name='conditions_satisfied',
        ),
    ]
