# Generated by Django 3.0.5 on 2020-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0010_workflow_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='created_by',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(to='project_management_portal.Developer'),
        ),
    ]
