# Generated by Django 3.0.5 on 2020-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0011_auto_20200629_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='developers',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
