# Generated by Django 3.0.5 on 2020-06-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0012_auto_20200629_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developers',
            new_name='Developer',
        ),
    ]
