# Generated by Django 3.0.5 on 2020-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0013_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
