# Generated by Django 3.0.5 on 2020-06-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0015_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplevel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupLevel',
        ),
    ]
